/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package projet_demineurca;

/**
 *
 * @author cleme
 */
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

public class InterfaceJeu extends javax.swing.JFrame {
    private GrilleDeJeu grilleDeJeu; // Grille logique
    private JPanel panneauGrille; // Panneau pour afficher la grille

    public InterfaceJeu() {
        setTitle("Jeu Démineur");
        setSize(600, 600);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLayout(null);

        // Initialisation de la grille logique (10x10 avec 20 bombes)
        grilleDeJeu = new GrilleDeJeu(10, 10, 20);

        // Création et affichage de la grille graphique
        initialiserGrilleGraphique();
    }

    private void initialiserGrilleGraphique() {
        panneauGrille = new JPanel();
        panneauGrille.setBounds(50, 50, 400, 400);
        panneauGrille.setLayout(new GridLayout(10, 10)); // Grille 10x10

        // Ajouter les boutons à la grille graphique
        for (int i = 0; i < grilleDeJeu.getNbLignes(); i++) {
            for (int j = 0; j < grilleDeJeu.getNbColonnes(); j++) {
                JButton bouton = new JButton(); // Création du bouton
                int ligne = i; // Indice de la ligne
                int colonne = j; // Indice de la colonne

                // Ajouter un événement de clic au bouton
                bouton.addActionListener(e -> {
                    try {
                        grilleDeJeu.revelerCellule(ligne, colonne); // Révéler la cellule logique
                        bouton.setText(Integer.toString(
                            grilleDeJeu.matriceCellules[ligne][colonne].getNbBombesAdjacentes())); // Afficher les bombes adjacentes
                    } catch (RuntimeException ex) {
                        bouton.setText("B"); // Afficher une bombe si déclenchée
                        System.out.println("Partie terminée !");
                    }
                });

                panneauGrille.add(bouton); // Ajouter le bouton au panneau
            }
        }

        add(panneauGrille); // Ajouter le panneau à la fenêtre
    }

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            new InterfaceJeu().setVisible(true);
        });
    }
}


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
